stages:
  - build
  - test
  - package
  - deploy

# This is for cache - .m2/repository/ (maven will save files in project directory, not in home folder)
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/
    - main-server/target/
    - breakage-server/target/
    - gateway/target/
    - common-module/target/

build-job:
  stage: build
  image: maven:3.9-amazoncorretto-21-alpine
  before_script:
    - echo "==================== start build-job ===================="
  after_script:
    - echo "==================== finish build-job ===================="
  script:
    - mvn clean compile
#  only:
#    - main

test-job:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  image: maven:3.9-amazoncorretto-21-alpine
  services:
    - docker:27-dind
  before_script:
    - echo "==================== start test-job ===================="
  after_script:
    - echo "==================== finish test-job ===================="
  script:
    - mvn test
  only:
    - main

package-job:
  stage: package
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  image: maven:3.9-amazoncorretto-21-alpine
  services:
    - docker:27-dind
  before_script:
    - echo "==================== start package-job ===================="
  after_script:
    - echo "==================== finish package-job ===================="
  script:
    - mvn package

deploy-job:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://docker:2375   # без TLS
#    DOCKER_TLS_CERTDIR: "/certs"          # включает TLS и указывает корень для сертификатов
#    DOCKER_HOST: tcp://docker:2376         # TLS-порт демона
#    DOCKER_TLS_VERIFY: 1                    # включить проверку TLS
#    DOCKER_CERT_PATH: "/certs/client"       # где клиент ищет сертификаты
  image: docker:27-cli
  services:
    - name: docker:27-dind
      alias: docker                         # гарантирует, что имя хоста — docker
      command: ["dockerd", "-H", "tcp://0.0.0.0:2375"]
  before_script:
    - echo "==================== start deploy-job ===================="
    - echo "==================== start check the connection with the docker demon ===================="
    - ls -la /certs/client || true
    - docker info || true
    - docker version || true
    - echo "==================== finish check the connection with the docker demon ===================="
  after_script:
    - echo "==================== finish deploy-job ===================="
  script:
    - docker compose build
    - docker compose up -d