# version: '3.8'
services:
  gateway:
    build: ./gateway
    image: th-gateway-image
    restart: on-failure
    container_name: th-gateway-container
    ports:
      - "12344:12344"
    depends_on:
      - db-postgres
    environment:
      MAIN_SERVER_URL: http://main-server:12333
      TZ: Europe/Moscow

  main-server:
    build: ./main-server
    image: th-main-image
    restart: on-failure
    container_name: th-main-server-container
    ports:
      - "12333:12333"
    depends_on:
      - db-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/technical_helper
      #      - DB_NAME=later
      #      - POSTGRES_USER=root
      #      - POSTGRES_PASSWORD=root
      #      - DB_HOST=db
      #      - DB_PORT=5432
      TZ: Europe/Moscow

  db-postgres:
    image: postgres:17-alpine
    restart: on-failure
    container_name: postgresql-container
    ports:
      - "12222:5432"
    volumes:
      - thdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: technical_helper
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sapassword
#      - POSTGRES_DB_HOST=localhost
#      - POSTGRES_DB_PORT=5432
#      - POSTGRES_DB_NAME=technical_helper


  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4-container
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgpassword
    ports:
      - "12221:80"
    depends_on:
      - db-postgres
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  thdata:
  pgadmin: